### ISSUE TITLE
Local storage pools

### ISSUE THREAD

**Issue by luissimas** [cloudlabs-ufscar/incus-charm#3]
# Description

Local storage pools are mostly used for standalone deployments, and we should provide a way to configure and provision local storage pools on the charm. I've started doing this while doing another task, but it turned out to be much more work that I expected, so I'm keeping this on a new issue.

This is my initial implementation of what we'll need on `charmcraft.yaml`:

```yaml
config:
  options:
    create-local-storage-pool:
      description: |
        Whether to create a local storage pool.
      type: boolean
      default: true
    local-storage-pool-driver:
      description: |
        The storage driver to use for the local storage pool.

        Acceptable values are: "dir", "btrfs" and "zfs".
      type: string
      default: zfs
    local-storage-pool-device:
      description: |
        The block device in which to create the local storage pool.

        Can be either device name such as "sdx" or the full path to
        the device such as "/dev/sdx".

        This config option takes precedence over the `local` storage. When
        this option is not specified and no storage is provided, a loop
        device or directory on the root disk will be created for the storage
        pool, depending on the driver specified by `local-storage-pool-driver`.
      type: string

storage:
  local:
    type: block
    description: |
      Block device that will be used to create the local storage pool if
      specified by `create-local-storage-pool`.

      This device will not be used if the `local-storage-pool-device` is specified.

      When no storage is provided and the config option `local-storage-pool-device`
      is not specified, a loop device or directory on the root disk will be created
      for the storage pool, depending on the driver specified by
      `local-storage-pool-driver`.
    minimum-size: 5G
    multiple:
      range: 0-1
```

# Definition of done

- [x] The config options and storage mentioned in the above snippet are present in the charm
- [x] When Incus is bootstrapped by the charm, those options are used to create a local storage pool and add it to the `default` profile
- [x] If the storage is added after Incus's bootstrap and there isn't any storage pool created, the charm should create a new storage pool with the options provided and add it to the `default` profile

# Resources

https://juju.is/docs/sdk/charmcraft-yaml#heading--storage
https://linuxcontainers.org/incus/docs/main/explanation/storage/#storage-location
https://linuxcontainers.org/incus/docs/main/reference/storage_drivers/#recommended-setup
https://charmhub.io/data-platform-libs/libraries/data_models
